### ISSUE TITLE
Mpesa Migrations

### ISSUE THREAD

**Issue by el-capuchon** [DrH97/mpesa#1]
Bro my Bruv!

Can there be an option to choose which tables to migrate and which ones not to. For example currently I only need the stk_requests and stk_callbacks tables but running the current mpesa migrations includes bulk tables, c2b tables etc... Ama zinakeep stk tables company?👻

Si utafanya ile kitu bro...😎

**Comment by DrH97** [comment]
This is influenced by how Laravel registers the migrations of a package.
```php
$this->loadMigrationsFrom(__DIR__ . '/Database/Migrations');
```

For now, the solution may be to delete the unneeded tables.

It would be possible for instance if they added a second parameter to the command above to specify groups for migrations e.g.

```php
$this->loadMigrationsFrom(__DIR__ . '/Database/Migrations', DEFAULT_GROUP);
```

**Comment by DrH97** [comment]
Also, using laravels default path specifier should yield the needed results.

```php
php artisan migrate:refresh --path=/database/migrations/fileName.php
```
